name: icon_font_generator
version: 3.0.0
homepage: https://github.com/rbcprolabs/icon_font_generator
description: Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  recase: ^4.0.0
  args: ^2.3.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1

executables:
  icon_font_generator: icon_font_generator
