name: icon_font_generator
version: 4.0.0
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/ScerIO/icon_font_generator

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.0
  dart_style: ^2.3.0
  logger: ^1.3.0
  meta: ^1.8.0
  path: ^1.8.2
  path_parsing: ^1.0.1
  recase: ^4.1.0
  vector_math: ^2.1.4
  xml: ^6.2.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  
executables:
  generator: generator