name: icon_font_generator
author: Serge Shkurko <SergeShkurko@outlook.com>
version: 1.0.0
homepage: https://github.com/rbcprolabs/icon_font_generator
description: Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class.
environment: 
  sdk: '>=2.3.0-dev.0.5 <3.0.0'
dependencies: 
  recase: ^2.0.1
  args: ^1.5.2
  meta: ^1.1.6
  path: ^1.6.4
dev_dependencies: 
  pedantic: ^1.5.0
executables: 
  icon_font_generator: icon_font_generator
